### ISSUE TITLE
How do you step over a line?

### ISSUE THREAD

**Issue by dsdeiz** [krakjoe/phpdbg#131]
Hey all,

Not exactly sure if I got the right term but I am wondering how to step over a line? E.g. I have this:

```php
function bar() {
  return 5;
}

function foo() {
  $b = bar();
  return $b;
}
```

Breakpoint is set at `foo()`. If I would use `s` it would step into `bar()`. I'm expecting it to just step over that function call.

I'm guessing this is modeled from gdb? I haven't used that tool but based on the docs, it has this option:

> set step-mode off
Causes the step command to step over any functions which contains no debug information. This is the default.

**Comment by felipensp** [comment]
You must to use the 'until' command.

**Comment by dsdeiz** [comment]
It looks like this goes to the next breakpoint rather than going through the next line in the stack frame which is `return $b` in my case.

**Comment by bwoebi** [comment]
I'll add functionality for that in PHP 7.

**Comment by bwoebi** [comment]
Added as `next` command in PHP 7 source tree.
