### ISSUE TITLE
Terminate on ctrl-c

### ISSUE THREAD

**Issue by bilogic** [krakjoe/phpdbg#147]
Can phpdbg terminate upon pressing of ctrl-c?
Helps when you have made changes and want to debug again from start

**Comment by bilogic** [comment]
I realized it stops on ctrl-z. thanks.

**Comment by bilogic** [comment]
ctrl-z does not terminate, phpdbg stays running in the memory. please consider implemention ctrl-c. Thank you.

**Comment by bwoebi** [comment]
Uhm, doesn't phpdbg stop at the next opline when pressing ctrl+c? AFAIK, that's the default behaviors debuggers like lldb or gdb also expose. To quit, press ctrl+c, and then type `q`+enter.
