### ISSUE TITLE
Support phpdbg_start_oplog

### ISSUE THREAD

**Issue by raziel057** [krakjoe/phpdbg#150]
Would it be possible to replicate the new feature integrated to phpdbg for PHP 7 in php5-dbg in order to be able to use it as a replacement of xdebug to get the code coverage using PHPunit?

Currently the method 'phpdbg_start_oplog' is missing. A check is done on this method in https://github.com/sebastianbergmann/environment/blob/master/src/Runtime.php

**Comment by bwoebi** [comment]
No, not really. I'm bound here to the PHP release process which doesn't allow me to add a bit bigger features to PHP 5.6.

Sorry, you'll have to use PHP 7 for it.

**Comment by raziel057** [comment]
Ok no problem. Thanks for the reply. It was also to check if there were the same issue that in PHP7 when runing tests with --process-isolation.

```
phpdbg -qrr /usr/local/bin/phpunit -v -c app/ --filter=AuthenticationControllerTest --process-isolation
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.

Runtime:       PHPDBG 7.0.0-5+deb.sury.org~trusty+1
Configuration: myapp/phpunit.xml.dist

mmap() failed: [12] Cannot allocate memory
[PHP Fatal error:  Out of memory (allocated 23756800) (tried to allocate 9622369213780901352 bytes) in phar:///usr/local/bin/phpunit/phpunit/Util/GlobalState.php on line 166]
```

I have no problem without "process isolation" or with "process isolation" but without phpdbg:

```
phpdbg -qrr /usr/local/bin/phpunit -v -c app/ --filter=AuthenticationControllerTest
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.

Runtime:       PHPDBG 7.0.0-5+deb.sury.org~trusty+1
Configuration: /srv/ic2m/novento/app/phpunit.xml.dist

...

Time: 1.86 seconds, Memory: 76.66Mb

OK (7 tests, 22 assertions)
```
