### ISSUE TITLE
phpdbg_get_executable() with the "files" option can additionally return subsets of the executable lines of files that are not requested in the "files" option

### ISSUE THREAD

**Issue by ezzatron** [krakjoe/phpdbg#152]
I'm not sure if this is intended behaviour since I couldn't find any documentation on `phpdbg_get_executable()`.

The issue is this: when `phpdbg_get_executable()` is called with the "files" option specified, it can return details of *other* files as well as the ones specified in the "files" option. In addition, these additional files may list only a *subset* of the actual executable lines in the additional files.

This, compounded with the way [sebastianbergmann/php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) uses PHPDBG, causes a bug where lines are marked as not covered when they should be covered. This is because php-code-coverage uses an array merge on multiple calls to `phpdbg_get_executable()`, and when the "additional" files are returned with only a subset of their executable lines, the missing lines lose their coverage information.

I've tried to create a small reproducible test case, but I'm having no luck. My use-case is a large (1.8K tests) PHPUnit test suite running test coverage under PHP 7 PHPDBG. I don't even know if this is intended behaviour, or what the root cause is.

Can anyone with a bit more PHPDBG knowledge shed some light on the issue?

See also sebastianbergmann/php-code-coverage#421.

**Comment by bwoebi** [comment]
A guess, when looking at source code: https://github.com/php/php-src/blob/65ef7f8c33345bb40f0068604ad85555cadc9b44/sapi/phpdbg/phpdbg.c#L555

The code is not checking for whether the functions of the class are in the same file (only whether the class was declared in that file). I guess in case you are using traits or inheritance, this will return _all_ functions of the class regardless of the file. Can you please verify whether this is the exact issue you are encountering? @ezzatron

**Comment by ezzatron** [comment]
Yes! It's inheritance. Here's a reproducible example:

**a.php**:

```php
<?php

class a
{
    function a() {
        echo 'a';
    }
}
```

**b.php**:

```php
<?php

class b extends a
{
    function b() {
        echo 'b';
    }
}
```

**test.php**:

```php
<?php

require __DIR__ . '/a.php';
require __DIR__ . '/b.php';

var_dump(phpdbg_get_executable(['files' => [__DIR__ . '/b.php']]));
```

Place all files in a directory and run `phpdbg -qrr test.php`.

**Expected output**:

```php
array(1) {
  ["/Users/erin/Projects/eloquent/phony/b.php"]=>
  array(1) {
    [6]=>
    int(0)
  }
}
```

**Actual output**:

```php
array(2) {
  ["/Users/erin/Projects/eloquent/phony/b.php"]=>
  array(1) {
    [6]=>
    int(0)
  }
  ["/Users/erin/Projects/eloquent/phony/a.php"]=>
  array(1) {
    [6]=>
    int(0)
  }
}
```

**Comment by bwoebi** [comment]
Thanks. Fixed via https://github.com/php/php-src/commit/1a01a5ec83394fa8375d70075eeaf496078e3e11 :-)

**Comment by ezzatron** [comment]
Awesome! Thanks!
