### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by theofidry** [krakjoe/phpdbg#154]
I'm running a test suite with PHPUnit 5.3.1 on PHP 7.0.4 on Travis. It takes 4.21 seconds and 76.00Mb to run on Travis without xdebug unabled.

When I used phpdbg to have the code coverage, i.e. running `phpdbg -qrr vendor/bin/phpunit`, a memory exhaustion error:

```
[PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65536 bytes) in /my/php/file on line 129]
```

It is also worth noting that this was working fine before starting to add PHP7 code (we were already on PHP7 before, but still PHP5.6 compatible).

Unfortunately I can't install phpdbg locally so I can't reproduce it outside of Travis yet.

**Comment by bwoebi** [comment]
Could you please point me to your repository so that I may check it out and debug?

**Comment by theofidry** [comment]
Sadly it is a private repository :(

**Comment by bwoebi** [comment]
Then I'm sorry, without reproduce case, I'm unable to do anything.

**Comment by theofidry** [comment]
Update on the issue.

I've spotted a test case that can be problematic: https://github.com/theofidry/phpdbg-bug-demo. It is fairly simple and I don't see why it would cause any issue. However, fact is that:

- Tests stops (due to memory limit reached) when arriving to that step
- Marking [this test](https://github.com/theofidry/phpdbg-bug-demo/blob/master/WhoopsDebugRendererTest.php) as skipped, our test suite pass without any problem

Now what's weird is:

- I ran my whole test suite (without phpdbg). The highest memory peak reached is `4534.51Kb` (the very first test, due to the bootstrapping I guess) but otherwise everything is more around ~100Kb`
- I tried to run the suspect test with phpdbg alone (the link repository you have), nothing wrong apprears sadly

It's also worth noting that the test you see is pretty representative of what our tests (for unit tests) looks like: there is no application started, lots of mocking with Prophecy, not even 1 static property.

I understand that not having access to the code makes it nearly impossible to help, but I still thought it would be worth to share those results.

**Comment by theofidry** [comment]
Solved the issue by removing the memory limit on travis. As I can't really debug more than that, will close the issue.

**Comment by teohhanhui** [comment]
Possibly related to phpspec/prophecy#96

**Comment by theofidry** [comment]
@teohhanhui it might be interesting to do some profiling on Prophecy indeed. I'm sure there's things to improve on PHPUnit side as well but I don't really want to dig into that either :P
