### ISSUE TITLE
get_included_files() is returning entries that are definitely not file paths

### ISSUE THREAD

**Issue by ezzatron** [krakjoe/phpdbg#156]
I use phpdbg for PHPUnit code coverage. A recent build on Travis saw a **huge** drop in coverage %, way more than the code change should have warranted. I think it coincided with the update to PHP 7.0.7 / phpdbg 0.5.0.

After digging around in the internals of `php-code-coverage`, I found that the call to `get_included_files()` was returning a very strange result:

```
array(130) {
  [0]=>
  string(69) "/path/to/eloquent/phony/vendor/composer/autoload_real.php"
  [1]=>
  string(71) "/path/to/eloquent/phony/vendor/composer/autoload_static.php"
  [2]=>
  string(45) "" does not extend PHPUnit_Framework_TestCase."
  [3]=>
  string(82) "/path/to/eloquent/phony/test/suite/Assertion/AssertionRendererTest.php"
  [4]=>
  string(75) "/path/to/eloquent/phony/vendor/simpletest/simpletest/dumper.php"
  
  // snip...
```

Now, obviously "does not extend PHPUnit_Framework_TestCase." is not a file path. In fact, it's part of an exception message that *can* be thrown by PHPUnit in the constructor of `PHPUnit_Framework_TestSuite`. In any case, it's pretty clear that something's not right here.

**Comment by bwoebi** [comment]
https://bugs.php.net/bug.php?id=72284

yeah :-( My bad, sorry.

**Comment by ezzatron** [comment]
No worries, good to know you got it sorted. Thanks!
