### ISSUE TITLE
Unable to set breakpoints in files containing a space in the pathname

### ISSUE THREAD

**Issue by nikolaikrill** [krakjoe/phpdbg#157]
I've tried surrounding the file path in quotes and escaping the space, but it always fails with:
[The command "break" expected condition and got file or file opline at parameter 2]

It's clearly a bug.

**Comment by bwoebi** [comment]
Not quite a bug, but not supported yet. Thanks, I'll allow that for 7.0.9. (with quotes and backslash-escaping)

**Comment by bwoebi** [comment]
Erm, were you using PHP 5.6? In PHP 7 this had been fixed since a long time actually…
