### ISSUE TITLE
Nothing to execute! (and other less-than-useful "error" messages)

### ISSUE THREAD

**Issue by AnrDaemon** [krakjoe/phpdbg#162]
```
"C:\usr\sbin\php-7.1.0\phpdbg.exe" -rrE vendor\phpunit\phpunit\phpunit -- --verbose --stop-on-failure --stop-on-incomplete --stop-on-error tests\Composer\Test\Repository\PathRepositoryTest.php
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
Cannot open file "--verbose.php".

"C:\usr\sbin\php-7.1.0\phpdbg.exe" -rrE -- vendor\phpunit\phpunit\phpunit -- --verbose --stop-on-failure --stop-on-incomplete --stop-on-error tests\Composer\Test\Repository\PathRepositoryTest.php
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
[Nothing to execute!]
```

I'm not quite sure how to… treat this… behavior.
1. Why on earth it alters the arguments? ("--verbose.php" ? What the hell?)
2. How to tell it that I want to load this specific file?
3. Why it doesn't react to `--help`, of all the questions?

**Comment by bwoebi** [comment]
Uhm, you forgot to put quotes around the path (or use forward slashes) I guess?

**Comment by AnrDaemon** [comment]
> you forgot to put quotes around the path (or use forward slashes)

```
$ C:\usr\sbin\php-7.1.r33e96c9\phpdbg.exe -rrE "vendor/phpunit/phpunit/phpunit" -- --stop-on-failure --stop-on-incomplete --stop-on-error tests\Composer\Test\Downloader\PearPackageExtractorTest.php
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
Cannot open file "--stop-on-failure.php".

$ C:\usr\sbin\php-7.1.r33e96c9\phpdbg.exe -rrE -- "vendor/phpunit/phpunit/phpunit" -- --stop-on-failure --stop-on-incomplete --stop-on-error tests\Composer\Test\Downloader\PearPackageExtractorTest.php
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
[Nothing to execute!]
```

I'm not quite sure if it made a difference.

**Comment by bwoebi** [comment]
The path at the end of the comment too?

**Comment by AnrDaemon** [comment]
Why?

**Comment by bwoebi** [comment]
Because the error you get indicates that some escape sequences have been triggered.

**Comment by AnrDaemon** [comment]
Ok, you're not paying attention, I see.
```
$ C:\usr\sbin\php-7.1.r33e96c9\phpdbg.exe -rrE "vendor/phpunit/phpunit/phpunit" -- --stop-on-failure --stop-on-incomplete --stop-on-error
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
Cannot open file "--stop-on-failure.php".

$ C:\usr\sbin\php-7.1.r33e96c9\phpdbg.exe -rrE -- "vendor/phpunit/phpunit/phpunit" -- --stop-on-failure --stop-on-incomplete --stop-on-error
[Welcome to phpdbg, the interactive PHP debugger, v0.5.0]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
[Nothing to execute!]
```
Please point, where it could possible "trigger an escape sequence" ?…

**Comment by bwoebi** [comment]
Ah, you confused me, because that error came from phpunit, not form phpdbg.

Well, try without `--` at all or only at the end, before the actual file (you put a `--` behind the `phpunit` in the command in any case and thus phpunit was trying to interpret the first arg after that as a file):

`C:\usr\sbin\php-7.1.0\phpdbg.exe" -rrE vendor\phpunit\phpunit\phpunit --verbose --stop-on-failure --stop-on-incomplete --stop-on-error -- tests\Composer\Test\Repository\PathRepositoryTest.php`

There is indeed a bug regarding `--` in phpdbg though, will fix that soon (your second case should output `Cannot open file "--stop-on-failure.php".`. (The error message from phpdbg would have been `[Could not open file /path/to/file]`)

**Comment by AnrDaemon** [comment]
Ok, then how to set up command line arguments for a script I'm debugging?

**Comment by bwoebi** [comment]
As long as your filename doesn't start with a dash (`-`), just put it last.

Btw. you do realize that the `-E` option is step-on-eval?
phpdbg in general just takes the first argument which isn't part of the options as filename and the following args as args to the php script.

You probably want:

`C:\usr\sbin\php-7.1.0\phpdbg.exe" -qrr vendor\phpunit\phpunit\phpunit --verbose --stop-on-failure --stop-on-incomplete --stop-on-error -- tests\Composer\Test\Repository\PathRepositoryTest.php`

**Comment by AnrDaemon** [comment]
Last as in - after all of its arguments?… That makes very little sense.

**Comment by AnrDaemon** [comment]
Ok, I got it doing something. Thanks.
It is still very fragile, but will work for my immediate needs.
And yes, I'm aware that -E is a step-through-eval.
