### ISSUE TITLE
phpdbg remote debugging can not work

### ISSUE THREAD

**Issue by sarla999** [krakjoe/phpdbg#164]
php version is PHP 7.1.0-5+deb.sury.org~trusty+1
phpdbg version is v0.5.0

when I use remote debugging , phpdbg can not bind stdout prot 8000 when I use phpdbg -l4000/8000 or phpdbg -l4000/8000 -a
but php56 and phpdbg v0.4.0 have work.

**Comment by bwoebi** [comment]
This changed in v0.5. It will print stdout on the same port where it waits for stdin.

Just use `phpdbg -l4000 -a` and it will print on port 4000 as well as listen for commands on port 4000.

**Comment by sarla999** [comment]
Hi bwoebi , How do I adaptation this change for use phpdbg-ui ?  stdin and stdout both choose 4000? 

It still not work, I can not get any output.
