### ISSUE TITLE
Change criteria for an "until" stop

### ISSUE THREAD

**Issue by TerryE** [krakjoe/phpdbg#80]
At the moment if you are on file **F** line **N**, an **until** command skips any breaks or steps until executing an opcode on line **F:N+1**.  This causes counter-intuitive behaviour in the following case:
```
 >  if($cond) {   /* which evaluates as false */
        ...
    }
```
Line N+1 is not executed next so the execution skips forward either to completion, or on  a subsequent pass when `$cond` evaluates as true.  Both of these will be very confusing for the user.

`gdb` uses the following interpretation for **until**

> `Execute until the program reaches a source line greater than the current`

I suggest that we modify the interpretation of **until** to be: execute until the program reaches a source line greater than the current _within the current stack frame_, or until exiting the current frame.  In this way **until** will become a proper "step forward" command.

**Comment by bwoebi** [comment]
This is the current behavior of `until` now. [There also were issues related to exceptions... All fixed now. - In PHP 7 source tree.]
